// <auto-generated />
using Hardware;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hardware.Migrations.CustomerDbcontextMigrations
{
    [DbContext(typeof(CustomerDbcontext))]
    [Migration("20250306101454_CustomerDb")]
    partial class CustomerDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Hardware.Customers", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomerId");

                    b.ToTable("customers");
                });
#pragma warning restore 612, 618
        }
    }
}
